actors:
  punchdrunker:
    image_url: /images/actors/punchdrunker.jpg
    name: punchdrunker
    url: https://twitter.com/punchdrunker
  atsushisakai:
    image_url: /images/actors/atsushisakai.jpg
    name: atsushisakai
    url: https://twitter.com/_atsushisakai
author: punchdrunker
description: みてねのエンジニアの日常をお届けします
description_long: みてねのエンジニアの日常をお届けするポッドキャスト
email: takafumi.nanao@mixi.co.jp
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-164155974-1
hashtag: mitene_tech_radio
itunes_podcast_url:
keywords: mitene,familyalbum,mixi
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: みてね技術放送局
url: http://example.com
